# -*- coding: utf-8 -*-
"""QR Maker .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WnQ2t8Uza1Zu-PXbfN2Gp8ajcV7ct4fG
"""

pip install qrcode

pip install image

import qrcode
import image

qr = qrcode.QRCode(
    version = 15,
    box_size = 10,
    border = 5)

data = "https://www.youtube.com/results?search_query=weather+calculation+website+using+python+with+full+code"


qr.add_data(data)
qr.make(fit = True)
img = qr.make_image(fill="black",back_color= "white")
img.save("test.png")